name: Autoformat and Lint Wiki

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  merge_group:

jobs:

  autoformat-and-lint-wiki:
  
    name: Autoformat and Lint Wiki

    runs-on: ubuntu-latest

    steps:

    - name: 🛎 Checkout Wiki
      if: github.event.pull_request.user.login != 'dependabot[bot]'
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        token: ${{ secrets.WORKFLOW_COMMIT }}

    - name: 🛎🤖 Bot Checkout Wiki
      if: github.event.pull_request.user.login == 'dependabot[bot]'
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
    
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: 📦 Install dependencies
      run: pip install -r .github/requirements.txt
    
    - name: 🧼 Format markdown
      run: mdformat .

    - name: ✅ Commit code format changes
      if: github.event.pull_request.user.login != 'dependabot[bot]'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Autoformat markdown"

    - name: 🔺 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3
        bundler-cache: true

    - name: 📦 Install dependencies
      run: gem install mdl

    - name: 🧹 Lint
      run: mdl -g .