name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

# Change version values here
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: spectral-shift

jobs:

  build:
    strategy:
      matrix:
        platform: [ Windows, Linux, Mac ]

    name: Build ${{ matrix.platform }}

    runs-on: ubuntu-latest
    container:
      image: microbob/godot-exporter:latest

    steps:

    - name: 🛎 Checkout
      uses: actions/checkout@v3
    
    - name: 📝 Set export name
      run: EXPORT_NAME=${{ env.EXPORT_NAME }}

    - name: Test Godot
      run: godot --version
    
    - name: Test Godot 2
      run: godot -d -q

    - name: 📦 Build
      run: source /root/build/${{ matrix.platform }}-export.sh

    - name: ⬆️ Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.platform }}
        path: ../build/${{ matrix.platform }}