name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

# Change version values here
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: spectral-shift

jobs:

  build:
    strategy:
      matrix:
        platform: [ Windows, Linux, Mac ]

    name: Build ${{ matrix.platform }}

    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.4

    steps:

    - name: 🛎 Checkout
      uses: actions/checkout@v3
    
    - name: 💾 Cache Godot
      id: cache-gd
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/godot
        key: ${{ runner.os }}-gd-${{ env.GODOT_VERSION }}

    - name: Move build templates
      run: |
        mkdir -v -p ~/.local/share/godot/templates
        mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable

    - if: matrix.platform == 'Windows'
      name: Build Windows
      run: |
        mkdir -v -p build/Windows
        godot -v --export "Windows Desktop" ../build/Windows/$EXPORT_NAME.exe
    
    - if: matrix.platform == 'Linux'
      name: Build Linux
      run: |
        mkdir -v -p build/Linux
        godot -v --export "Linux/X11" ../build/Linux/$EXPORT_NAME.x86_64
    
    - if: matrix.platform == 'Mac'
      name: Build Mac
      run: |
        mkdir -v -p build/Mac
        godot -v --export "Mac OSX" ../build/Mac/$EXPORT_NAME.dmg

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.platform }}
        path: build/${{ matrix.platform }}