name: Generate Documentation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  generate-docs:
    
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3

    - name: Cache Natural Docs
      id: cache-natural-docs
      uses: actions/cache@v3
      env:
        cache-name: cache-natural-docs-2.2
      with:
        path: "Natural Docs"
        key: ${{ runner.os }}-${{ env.cache-name }}
    
    - if: ${{ steps.cache-natural-docs.outputs.cache-hit == 'false' }}
      name: Install Natural docs if miss
      continue-on-error: false
      run: Invoke-WebRequest -Uri "https://www.naturaldocs.org/download/natural_docs/2.2/Natural_Docs_2.2.zip" -OutFile "nd.zip"; tar -xf nd.zip

    - name: Make export location
      run: md docs
    
    - name: Generate Docs
      shell: cmd
      run: call "Natural Docs\NaturalDocs.exe" .\.github\nd_config
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs
    
    
  deploy-docs:

    needs: [generate-docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'docs'