name: Generate Documentation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:

  generate-docs:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3

    - name: Download Natural Docs
      run: Invoke-WebRequest -Uri "https://www.naturaldocs.org/download/natural_docs/2.2/Natural_Docs_2.2.zip" -OutFile "nd.zip"

    - name: Extract
      run: tar -xf nd.zip

    - name: Make export location
      run: md docs
    
    - name: Build
      run: ls .\.github\nd_config\

    # - name: Build
    #   run: '.\Natural Docs\NaturalDocs.exe' .\.github\nd_config\