name: Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Download Godot
      run: wget https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_linux_server.64.zip
    
    - name: Extract Godot
      run: unzip Godot_v3.4.4-stable_linux_server.64.zip
    
    - name: Download Gut
      run: wget https://github.com/bitwes/Gut/archive/refs/tags/v7.3.0.zip

    - name: make addons extract location
      run: mkdir addons

    - name: Extract Gut
      run: unzip v7.3.0.zip -d addons/
    
    - name: Run Godot once
      run: ./Godot_v3.4.4-stable_linux_server.64 -e -d -q

    - name: Run tests
      run: ./Godot_v3.4.4-stable_linux_server.64 -d -s addons/gut/gut_cmdln.gd