name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  merge_group:

# Change version values here
env:
  GODOT_VERSION: 3.5.2
  GUT_VERSION: 7.4.1
  ASSETS_URL: https://res.cloudinary.com/dxgycuhlr/raw/upload/v1663640722/assets.tar_jdc4la.xz
  ASSETS_FILE_NAME: assets.tar_jdc4la.xz

jobs:

  gut-tests:
    name: Gut Tests
    runs-on: ubuntu-latest

    steps:
    
    - name: 🛎 Checkout
      uses: actions/checkout@v3

    - name: 💾 Cache Godot
      id: cache-gd
      uses: actions/cache@v3
      with:
        path: Godot_v${{ env.GODOT_VERSION }}-stable_linux_headless.64
        key: ${{ runner.os }}-gd-${{ env.GODOT_VERSION }}
    
    - name: 📦 Download Godot if cache miss
      if: steps.cache-gd.outputs.cache-hit != 'true'
      run: |
        wget https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_linux_headless.64.zip
        unzip Godot_v$GODOT_VERSION-stable_linux_headless.64.zip

    - name: 💾 Cache Gut
      id: cache-gut
      uses: actions/cache@v3
      with:
        path: addons
        key: ${{ runner.os }}-gut-${{ env.GUT_VERSION }}

    - name: 📦 Download Gut if cache miss
      if: steps.cache-gut.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/bitwes/Gut/archive/refs/tags/v$GUT_VERSION.zip
        unzip v$GUT_VERSION.zip
        mv Gut-$GUT_VERSION/addons addons
    
    - name: 💾 Cache Assets
      id: cache-assets
      uses: actions/cache@v3
      with:
        path: assets
        key: ${{ runner.os }}-assets-${{ env.ASSETS_URL }}
    
    - name: 📦 Download Assets if cache miss
      if: steps.cache-assets.outputs.cache-hit != 'true'
      run: |
        wget $ASSETS_URL
        tar -xvf $ASSETS_FILE_NAME
    
    - name: 📂 Open and process project
      run: ./Godot_v$GODOT_VERSION-stable_linux_server.64 -e --quit

    - name: 🧪 Run tests
      run: ./Godot_v$GODOT_VERSION-stable_linux_server.64 -d -s addons/gut/gut_cmdln.gd -gexit