name: Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    
    - name: 🛎 Checkout
      uses: actions/checkout@v3

    - name: Download Godot
      run: wget https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_linux_headless.64.zip
    
    - name: Extract Godot
      run: unzip Godot_v3.4.4-stable_linux_headless.64.zip
    
    - name: Download Gut
      run: wget https://github.com/bitwes/Gut/archive/refs/tags/v7.3.0.zip

    - name: Extract Gut
      run: unzip v7.3.0.zip
    
    - name: Rename into addons
      run: mv Gut-7.3.0 addons
    
    - name: show addons
      run: ls addons

    - name: show gut
      run: ls addons/gut
    
    - name: Run Godot Once
      run: ./Godot_v3.4.4-stable_linux_headless.64 -e -d -q

    - name: Run tests
      run: ./Godot_v3.4.4-stable_linux_headless.64 -d -q -s addons/gut/gut_cmdln.gd