name: Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Cache Godot
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: "Natural Docs"
        # Change key on Natural docs update
        key: ${{ runner.os }}-2.2
    
    - name: Install Natural docs if miss
      if: steps.cache-nd.outputs.cache-hit != 'true'
      # Change URL on Natural docs update
      run: Invoke-WebRequest -Uri "https://www.naturaldocs.org/download/natural_docs/2.2/Natural_Docs_2.2.zip" -OutFile "nd.zip"; tar -xf nd.zip

    - name: Download Godot
      run: wget https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_x11.64.zip
    
    - name: Extract Godot
      run: unzip Godot_v3.4.4-stable_x11.64.zip
    
    - name: Download Gut
      run: wget https://github.com/bitwes/Gut/archive/refs/tags/v7.3.0.zip

    - name: make addons extract location
      run: mkdir addons

    - name: Extract Gut
      run: unzip v7.3.0.zip -d addons/
    
    - name: List dir
      run: ls